export { catalogService } from './catalog.service';
export { cartService } from './cart.service';
export { accountService } from './account.service';
export { authService, type Session } from './auth.service';
export { checkoutService, type CheckoutInput, type CheckoutResult } from './checkout.service';
export { adminService } from './admin.service';
export { ApiError, clearAuthTokens, getAuthTokens, setAuthTokens } from './http';
export { API_BASE_PATH, API_URL, USE_MOCK } from './config';

/** Chaves centralizadas para o cache do TanStack Query. */
export const queryKeys = {
  categories: ['categories'] as const,
  products: (filters: unknown) => ['products', filters] as const,
  product: (slug: string) => ['product', slug] as const,
  featured: ['featured'] as const,
  related: (slug: string) => ['related', slug] as const,
  searchSuggest: (term: string) => ['search-suggest', term] as const,
  session: ['session'] as const,
  customer: ['customer'] as const,
  addresses: ['addresses'] as const,
  orders: ['orders'] as const,
  order: (id: string) => ['order', id] as const,
  pendingReviews: ['pending-reviews'] as const,
  admin: {
    dashboard: ['admin', 'dashboard'] as const,
    salesReport: (filters?: unknown) => ['admin', 'reports', 'sales', filters ?? {}] as const,
    productReport: (includeMargin?: boolean) => ['admin', 'reports', 'products', includeMargin ?? false] as const,
    stockReport: ['admin', 'reports', 'stock'] as const,
    customerReport: (filters?: unknown) => ['admin', 'reports', 'customers', filters ?? {}] as const,
    couponReport: ['admin', 'reports', 'coupons'] as const,
    abandonedCartReport: (olderThanHours?: number) => ['admin', 'reports', 'abandoned-carts', olderThanHours ?? 24] as const,
    reportExport: (id: string) => ['admin', 'reports', 'exports', id] as const,
    notifications: (filters?: unknown) => ['admin', 'notifications', filters ?? {}] as const,
    notification: (id: string) => ['admin', 'notifications', id] as const,
    automationJobs: (filters?: unknown) => ['admin', 'automation-jobs', filters ?? {}] as const,
    products: ['admin', 'products'] as const,
    product: (id: string) => ['admin', 'product', id] as const,
    categories: ['admin', 'categories'] as const,
    inventory: (filters?: unknown) => ['admin', 'inventory', filters ?? {}] as const,
    inventoryDetail: (variantId: string) => ['admin', 'inventory', 'detail', variantId] as const,
    inventoryMovements: (filters?: unknown) => ['admin', 'inventory', 'movements', filters ?? {}] as const,
    inventoryReservations: (filters?: unknown) => ['admin', 'inventory', 'reservations', filters ?? {}] as const,
    orders: ['admin', 'orders'] as const,
    ordersList: (filters?: unknown) => ['admin', 'orders', filters ?? {}] as const,
    order: (id: string) => ['admin', 'order', id] as const,
    orderHistory: (id: string) => ['admin', 'order', id, 'history'] as const,
    fiscalPreview: (id: string) => ['admin', 'order', id, 'fiscal-preview'] as const,
    orderPayments: (id: string) => ['admin', 'order', id, 'payments'] as const,
    orderWebhookEvents: (id: string) => ['admin', 'order', id, 'webhook-events'] as const,
    reviews: ['admin', 'reviews'] as const,
    customers: (filters?: unknown) => ['admin', 'customers', filters ?? {}] as const,
    customer: (id: string) => ['admin', 'customer', id] as const,
    customerAddresses: (id: string) => ['admin', 'customer', id, 'addresses'] as const,
    productPriceHistory: (id: string) => ['admin', 'product', id, 'price-history'] as const,
    coupons: ['admin', 'coupons'] as const,
    coupon: (id: string) => ['admin', 'coupons', id] as const,
    couponUsages: (id: string, filters?: unknown) => ['admin', 'coupons', id, 'usages', filters ?? {}] as const,
    couponDetailReport: (id: string) => ['admin', 'coupons', id, 'report'] as const,
    promotions: ['admin', 'promotions'] as const,
    promotion: (id: string) => ['admin', 'promotions', id] as const,
    promotionDetailReport: (id: string) => ['admin', 'promotions', id, 'report'] as const,
    users: ['admin', 'users'] as const,
    usersList: (filters?: unknown) => ['admin', 'users', filters ?? {}] as const,
    permissionCatalog: ['admin', 'permissions', 'catalog'] as const,
    employeePermissionMatrices: ['admin', 'permissions', 'employees'] as const,
    employeePermissionMatrix: (userId: string) => ['admin', 'permissions', 'employees', userId] as const,
    alerts: (filters?: unknown) => ['admin', 'alerts', filters ?? {}] as const,
    audit: ['admin', 'audit'] as const,
    auditList: (filters?: unknown) => ['admin', 'audit', filters ?? {}] as const,
    auditEntry: (id: string) => ['admin', 'audit', id] as const,
    integrations: ['admin', 'integrations'] as const,
    readiness: ['admin', 'readiness'] as const,
  },
};
